fix: eslint/tsconfig add precommit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,54 @@
-#!/usr/bin/env sh
-. "$(dirname -- "$0")/_/husky.sh"
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
 
-yarn lint
+echo "🚀 Kicking off pre-commit checks: Code Styling, Linting, Type-checking, and Building. 🚀"
+
+# Format code
+yarn run format && git add . || 
+(
+    echo "❌ Prettier Format Failed: 😬
+Run \"yarn run format\", stage your changes, and try again. 👨‍💻"
+    exit 1
+)
+
+# Check Prettier Standards
+yarn run format:check ||
+(
+    echo "❌ Prettier Check Failed: 😬
+Your code styling doesn't meet the project guidelines. 
+Run \"yarn run format\", stage your changes, and try again. 👨‍💻"
+    exit 1
+)
+
+# Check ESLint Standards
+yarn run lint ||
+(
+    echo "❌ ESLint Check Failed: 🚨
+Your code contains lint errors or warnings.
+Please fix them as indicated above, stage your changes, and try again. 🛠"
+    exit 1
+)
+
+# Check TypeScript Types
+yarn run type:check ||
+(
+    echo "❌ TypeScript Type Check Failed: 📝
+Your code has type errors.
+Fix them as outlined above, stage your changes, and try again. 🧐"
+    exit 1
+)
+
+# Attempt to Build the Project
+echo "🔨 Running build check: Attempting to build the project. 🏗"
+
+yarn run build ||
+(
+    echo "❌ Build Failed: 💔
+There was an error building the project.
+Review the errors above, make the necessary adjustments, and try again. 🤔"
+    exit 1
+)
+
+# If all checks pass, proceed with the commit
+echo "✅ All pre-commit checks passed! 🎉
+Your code is ready for the limelight. Proceeding with commit. 🚀"
